### ISSUE TITLE
How to compile on Ubuntu and Debian

### ISSUE THREAD

**Issue by Ibragimov** [GustavoPeredo/font-downloader#5]
Dear Gustavo,

Could you please, provide an information on how to install dependencies and build Font Downloader on Ubuntu and Debian, so I could build and test Tajik and Russian translations in there.

Thank you for prompt reply,
Victor Ibragimov

**Comment by GustavoPeredo** [comment]
Technically the build commands are the same, the only difference between debian/ubuntu and fedora build commands would be the dependencies, unfortunately it's been a while since I used debian or ubuntu, so I don't know the name of the packages, but I can guess them:

GTK Libraries: libgtk3.0-dev
Handy Libraries: libhandy1-dev
Gettext: gettext
Meson and ninja: build-essentials

That said it is preferable that you build the flatpak version, to do this you have to install flatpak and add flathub (you can see how to do this in your distro here: https://flatpak.org/setup/), then you have to install GNOME Builder, clone the repository, it should ask you to install missing SDKs, then click the Build button and lastly click the Export Package button (it should be highlighted), all you have to do then is install the flatpak.

PS: It seems to me that the translation is working already, I don't have the locale for Russian and Tajik, but Python strings are translated without the need for such locales, so it should be working fine.

**Comment by GustavoPeredo** [comment]
Tajik and Russians translations should have landed already in the flathub release version of the app, could you see whether they are working? Portuguese seems to be working fine :)

**Comment by Ibragimov** [comment]
https://github.com/GustavoPeredo/font-downloader/issues/3#issuecomment-702034319

**Comment by GustavoPeredo** [comment]
Thank you
